export const MAIN = '/main'
export const CATALOG = '/catalog/:product'
export const PRODUCT = '/products/:articul'
export const NEWS1 = '/news1'
export const COMMENTS = '/COMMENTS'
export const OFFER = '/offer'